#server
server:
  port: 8081
  servlet:
    context-path: /

spring:
  #database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/soen387_teamproject?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password:
  mvc:
    view:
      prefix: /WEB-INF/templates/
      suffix: .jsp
    static-path-pattern: /static/**

#mybatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.courseselect.po
  configuration:
    map-underscore-to-camel-case: true


#sql log
logging:
  level:
    com:
      courseselect:
        dao:
          debug